### ISSUE TITLE
Console Error (v1.2.0)

### ISSUE THREAD

**Issue by YukiAyase** [Katistic/AvatarStuff#1]
![image](https://user-images.githubusercontent.com/64414315/84328902-dc334800-abb5-11ea-9f27-ef4387c6965d.png)
I dunno what triggered this but I'm trying again
It didn't crash the game or anything, this error just popped up on the console

**Comment by Katistic** [comment]
It happens when initializing the slider for the avatar preview rotation. Everything should still work fine though

Edit: I will be fixing the error in the next update, until then sorry for the initial console spam
