### ISSUE TITLE
Bugs + Feature Request (v1.2.1 - v1.2.2)

### ISSUE THREAD

**Issue by fwenny** [Katistic/AvatarStuff#2]
When you click Get Public Avatars, the uploader name doesnt get updated after the first time.
Clicking Get Public Avatars in user info doesnt switch to Avatars, and instead opens a little menu at the bottom with the avatars, but you cannot interact with them.

Also, if possible, the rotation of avatar preview should stop completely, so you can easily look at avatars front with the slider instead of moving it all the time.

Thanks!

**Comment by Katistic** [comment]
Both Get Public Avatars bugs have already been fixed for the next update. As for stopping the rotation of the avatar preview, I'm having trouble with that. I'll keep trying, but don't expect anything too soon.

Thank you for reporting!
